import type { State } from "./types";
export const branding = {
  name: "Inventico",
  suffix: "calc",
  tagline: "Sua criatividade. Um negócio rentável.",
};
export const id = () => crypto.randomUUID();
export const defaults = (): State => ({
  version: 1,
  onboarded: false,
  filaments: [
    {
      id: "pla",
      name: "PLA • Natural",
      manufacturer: "Genérico",
      type: "PLA",
      color: "Natural",
      weight: 1000,
      price: 90,
      shipping: 0,
      extra: 0,
    },
  ],
  printers: [
    {
      id: "kobra",
      name: "Kobra S1 Combo",
      manufacturer: "Anycubic",
      model: "Kobra S1 Combo",
      price: 4000,
      accessories: 0,
      multicolor: 0,
      extra: 0,
      life: 10000,
      residual: 0,
      used: 0,
    },
  ],
  channels: [
    "Venda direta",
    "PIX",
    "Dinheiro",
    "Cartão",
    "WhatsApp",
    "Instagram",
    "Site",
    "Mercado Livre",
    "Shopee",
    "Amazon",
    "Outro",
  ].map((name, i) => ({
    id: `channel-${i}`,
    name,
    percent: 0,
    fixed: 0,
    payment: 0,
    paymentFixed: 0,
    extra: 0,
    shipping: 0,
    advertising: 0,
  })),
  settings: {
    kwh: 1,
    watts: 180,
    dryer: 0,
    additionalWatts: 0,
    hourly: 30,
    maintenance: 0.2,
    maintenanceMode: "simple",
    maintenanceItems: [],
    failure: 3,
    fixedItems: [],
    allocation: "pieces",
    allocationVolume: 100,
    taxMode: "none",
    taxPercent: 0,
    das: 0,
    marketingMode: "fixed",
    marketing: 0,
    minMargin: 20,
    targetMargin: 35,
    premiumMargin: 50,
    productiveHours: 20,
    daysMonth: 30,
    excellentHour: 15,
    goodHour: 8,
    minimumHour: 3,
  },
  simulation: {
    name: "Porta Papel Toalha Wave",
    category: "Casa & decoração",
    notes: "",
    grams: 341.09,
    hours: 11,
    minutes: 18,
    quantity: 1,
    price: 109.9,
    filamentId: "pla",
    printerId: "kobra",
    channelId: "channel-0",
    waste: [],
    labor: [
      {
        id: "preparo",
        name: "Preparação e acabamento",
        minutes: 20,
        scope: "job",
      },
    ],
    packaging: [],
    components: [],
    other: [],
    developmentHours: 0,
    developmentRate: 30,
    developmentUnits: 50,
    shippingReal: 0,
    shippingCharged: 0,
    discount: 10,
    wholesaleStep: 2,
  },
  products: [],
});
