export type Item = {
  id: string;
  name: string;
  quantity: number;
  cost: number;
  scope: "unit" | "job";
};
export type Filament = {
  id: string;
  name: string;
  manufacturer: string;
  type: string;
  color: string;
  weight: number;
  price: number;
  shipping: number;
  extra: number;
};
export type Printer = {
  id: string;
  name: string;
  manufacturer: string;
  model: string;
  price: number;
  accessories: number;
  multicolor: number;
  extra: number;
  life: number;
  residual: number;
  used: number;
};
export type Channel = {
  id: string;
  name: string;
  percent: number;
  fixed: number;
  payment: number;
  paymentFixed: number;
  extra: number;
  shipping: number;
  advertising: number;
};
export type Activity = {
  id: string;
  name: string;
  minutes: number;
  scope: "unit" | "job";
};
export type Waste = {
  id: string;
  name: string;
  value: number;
  mode: "g" | "%";
};
export type Settings = {
  kwh: number;
  watts: number;
  dryer: number;
  additionalWatts: number;
  hourly: number;
  maintenance: number;
  maintenanceMode: "simple" | "detailed";
  maintenanceItems: Item[];
  failure: number;
  fixedItems: Item[];
  allocation: "pieces" | "orders" | "hours";
  allocationVolume: number;
  taxMode: "none" | "mei" | "percent" | "custom";
  taxPercent: number;
  das: number;
  marketingMode: "fixed" | "percent";
  marketing: number;
  minMargin: number;
  targetMargin: number;
  premiumMargin: number;
  productiveHours: number;
  daysMonth: number;
  excellentHour: number;
  goodHour: number;
  minimumHour: number;
};
export type Simulation = {
  name: string;
  category: string;
  notes: string;
  grams: number;
  hours: number;
  minutes: number;
  quantity: number;
  price: number | null;
  filamentId: string;
  printerId: string;
  channelId: string;
  waste: Waste[];
  labor: Activity[];
  packaging: Item[];
  components: Item[];
  other: Item[];
  developmentHours: number;
  developmentRate: number;
  developmentUnits: number;
  shippingReal: number;
  shippingCharged: number;
  discount: number;
  wholesaleStep: number;
};
export type Snapshot = {
  settings: Settings;
  filaments: Filament[];
  printers: Printer[];
  channels: Channel[];
};
export type SavedProduct = {
  id: string;
  createdAt: string;
  input: Simulation;
  snapshot: Snapshot;
  result: Result;
};
export type State = Snapshot & {
  version: 1;
  onboarded: boolean;
  simulation: Simulation;
  products: SavedProduct[];
};
export type CostLine = { name: string; value: number };
export type Result = {
  hours: number;
  quantity: number;
  waste: number;
  consumption: number;
  materialPerGram: number;
  investment: number;
  lifePercent: number;
  humanHours: number;
  production: number;
  base: number;
  rate: number;
  fixedAllocated: number;
  monthlyFixed: number;
  lines: CostLine[];
  price: number;
  revenue: number;
  total: number;
  profit: number;
  margin: number;
  markup: number | null;
  markupPercent: number | null;
  roi: number | null;
  profitHour: number | null;
  revenueHour: number | null;
  costHour: number | null;
  costGram: number | null;
  breakEven: number | null;
  minimum: number | null;
  recommended: number | null;
  premium: number | null;
  contribution: number;
  monthlyBreakEven: number | null;
  paybackUnits: number | null;
  paybackHours: number | null;
  paybackDays: number | null;
  unitsDay: number | null;
  unitsWeek: number | null;
  unitsMonth: number | null;
  monthlyRevenue: number | null;
  monthlyProfit: number | null;
  status: string;
  message: string;
};
